version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  db:
    image: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: stocks
      POSTGRES_USER: stockuser
      POSTGRES_PASSWORD: stocks
    ports:
      - "5432:5432"
  frontend:
    build:
      context: ./freedom-calc-frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
volumes:
  postgres_data:
