const STOCKS :string[] = [
    "VIC", "VJC", "SSI", "HVN", "HSG", "BCM", "ABT", "IMP", "GAS", "TLG",
    "VPB", "EVF", "VNM", "VGI", "BIC", "HAX", "SIE", "SAP", "LHA", "PAH3.DE",
    "MBG", "BMW", "VOW3", "DHL", "ADS", "CON", "PUM", "AFX", "S92", "VGI",
    "NDX1", "NVDA", "V", "MA", "ORCL", "KO", "CRM", "MBG", "AMD", "INTC",
    "DIS", "NKE", "CAT", "UPS", "BA", "DB"
    ];


export const stockTickerToName: string[][]  =   [
    ["VIC", "Vingroup"],
    ["VJC", "VietJet"],
    ["SSI", "SSI Securities"],
    ["HVN", "Vietnam Airlines"],
    ["HSG", "Hoa Sen"],
    ["BCM", "Becamex"],
    ["ABT", "Bentre Aquaproduct Import"],
    ["IMP", "Inmexpharm"],
    ["GAS", "PV GAS"],
    ["TLG", "Thien Long"],
    ["VPB", "VP Bank"],
    ["EVF", "EVN"],
    ["VNM", "Vinamilk"],
    ["VGI.VN", "Viettel Investment"],
    ["BIC", "Vietnam Building Insurance"],
    ["HAX", "Hang Xanh Automobile"],
    ["SIE", "Siemens"],
    ["SAP", "SAP SE"],
    ["LHA", "Deutsche Lufthansa"],
    ["PAH3.DE", "Porsche"],
    ["MBG.DE", "Mercedes-Benz Group"],
    ["BMW", "Bayerische Motoren Werke"],
    ["VOW3", "Volkswagen"],
    ["DHL", "Deutsche Post"],
    ["ADS", "Adidas"],
    ["CON", "Continental"],
    ["PUM", "PUMA"],
    ["AFX", "Carl Zeiss Meditec"],
    ["S92", "SMA Solar Technology"],
    ["VGI.DE", "Bayer Aktiengesellschaft"],
    ["NDX1", "Nordex"],
    ["NVDA", "NVIDIA"],
    ["V", "Visa"],
    ["MA", "Mastercard"],
    ["ORCL", "Oracle"],
    ["KO", "The Coca-Cola"],
    ["CRM", "Salesforce"],
    ["MBG.US", "Netflix"],
    ["AMD", "Advanced Micro Devices"],
    ["INTC", "Intel Corporation"],
    ["DIS", "The Walt Disney Company"],
    ["NKE", "Nike"],
    ["CAT", "Caterpillar"],
    ["UPS", "United Parcel Service"],
    ["BA", "The Boeing Company"],
    ["DB", "Deutsche Bank"]
];


export default STOCKS;
